/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_agent (void)
{
  GtkWidget *agent;
  GtkWidget *fixed8;
  GtkWidget *fixed9;
  GtkWidget *fixed10;
  GtkWidget *fixed11;
  GtkWidget *fixed12;
  GtkWidget *fixed13;
  GtkWidget *fixed14;
  GtkWidget *fixed15;
  GtkWidget *entry3;
  GtkWidget *fixed16;
  GtkWidget *fixed17;
  GtkWidget *label6;
  GtkWidget *label4;
  GtkWidget *label5;
  GtkWidget *label8;
  GtkObject *spinbutton10_adj;
  GtkWidget *spinbutton10;
  GtkObject *spinbutton11_adj;
  GtkWidget *spinbutton11;
  GtkObject *spinbutton12_adj;
  GtkWidget *spinbutton12;
  GtkWidget *label32;
  GtkWidget *button2;
  GtkWidget *combobox8;
  GtkWidget *combobox9;
  GtkWidget *classcombo;
  GtkWidget *label33;
  GtkWidget *Quitter01;

  agent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (agent), _("agent"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (agent), fixed8);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_fixed_put (GTK_FIXED (fixed8), fixed9, 0, 0);
  gtk_widget_set_size_request (fixed9, 0, 0);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_fixed_put (GTK_FIXED (fixed8), fixed10, 0, 0);
  gtk_widget_set_size_request (fixed10, 0, 0);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_fixed_put (GTK_FIXED (fixed10), fixed11, 0, 0);
  gtk_widget_set_size_request (fixed11, 0, 0);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_fixed_put (GTK_FIXED (fixed8), fixed12, 0, 0);
  gtk_widget_set_size_request (fixed12, 0, 0);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_fixed_put (GTK_FIXED (fixed12), fixed13, 0, 0);
  gtk_widget_set_size_request (fixed13, 0, 0);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_fixed_put (GTK_FIXED (fixed8), fixed14, 0, 0);
  gtk_widget_set_size_request (fixed14, 0, 0);

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_fixed_put (GTK_FIXED (fixed14), fixed15, 0, 0);
  gtk_widget_set_size_request (fixed15, 0, 0);

  entry3 = gtk_entry_new ();
  gtk_widget_show (entry3);
  gtk_fixed_put (GTK_FIXED (fixed8), entry3, 24, 128);
  gtk_widget_set_size_request (entry3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3), 8226);

  fixed16 = gtk_fixed_new ();
  gtk_widget_show (fixed16);
  gtk_fixed_put (GTK_FIXED (fixed8), fixed16, 0, 0);
  gtk_widget_set_size_request (fixed16, 0, 0);

  fixed17 = gtk_fixed_new ();
  gtk_widget_show (fixed17);
  gtk_fixed_put (GTK_FIXED (fixed16), fixed17, 0, 0);
  gtk_widget_set_size_request (fixed17, 0, 0);

  label6 = gtk_label_new (_("A"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed8), label6, 264, 48);
  gtk_widget_set_size_request (label6, 96, 16);

  label4 = gtk_label_new (_("De"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed8), label4, 0, 40);
  gtk_widget_set_size_request (label4, 72, 24);

  label5 = gtk_label_new (_("Date de d\303\251part"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed8), label5, 16, 112);
  gtk_widget_set_size_request (label5, 120, 16);

  label8 = gtk_label_new (_("Classe"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed8), label8, 384, 112);
  gtk_widget_set_size_request (label8, 96, 16);

  spinbutton10_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton10 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton10_adj), 1, 0);
  gtk_widget_show (spinbutton10);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton10, 112, 248);
  gtk_widget_set_size_request (spinbutton10, 60, 27);

  spinbutton11_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton11 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton11_adj), 1, 0);
  gtk_widget_show (spinbutton11);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton11, 248, 248);
  gtk_widget_set_size_request (spinbutton11, 60, 27);

  spinbutton12_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton12 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton12_adj), 1, 0);
  gtk_widget_show (spinbutton12);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton12, 384, 240);
  gtk_widget_set_size_request (spinbutton12, 60, 27);

  label32 = gtk_label_new (_("adulte                         enfant                              bebe"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed8), label32, 104, 200);
  gtk_widget_set_size_request (label32, 344, 32);

  button2 = gtk_button_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed8), button2, 424, 304);
  gtk_widget_set_size_request (button2, 96, 29);

  combobox8 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox8);
  gtk_fixed_put (GTK_FIXED (fixed8), combobox8, 24, 72);
  gtk_widget_set_size_request (combobox8, 136, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("tun"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("it"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("mar"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox8), _("fr"));

  combobox9 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox9);
  gtk_fixed_put (GTK_FIXED (fixed8), combobox9, 304, 72);
  gtk_widget_set_size_request (combobox9, 136, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox9), _("tun"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox9), _("it"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox9), _("mar"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox9), _("fr"));

  classcombo = gtk_combo_box_new_text ();
  gtk_widget_show (classcombo);
  gtk_fixed_put (GTK_FIXED (fixed8), classcombo, 416, 136);
  gtk_widget_set_size_request (classcombo, 72, 24);
  gtk_combo_box_append_text (GTK_COMBO_BOX (classcombo), _("A"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (classcombo), _("B"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (classcombo), _("C"));

  label33 = gtk_label_new ("");
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed8), label33, 120, 16);
  gtk_widget_set_size_request (label33, 256, 24);

  Quitter01 = gtk_button_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (Quitter01);
  gtk_fixed_put (GTK_FIXED (fixed8), Quitter01, 24, 304);
  gtk_widget_set_size_request (Quitter01, 72, 29);

  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);
  g_signal_connect ((gpointer) Quitter01, "clicked",
                    G_CALLBACK (on_Quitter01_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (agent, agent, "agent");
  GLADE_HOOKUP_OBJECT (agent, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (agent, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (agent, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (agent, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (agent, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (agent, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (agent, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (agent, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (agent, entry3, "entry3");
  GLADE_HOOKUP_OBJECT (agent, fixed16, "fixed16");
  GLADE_HOOKUP_OBJECT (agent, fixed17, "fixed17");
  GLADE_HOOKUP_OBJECT (agent, label6, "label6");
  GLADE_HOOKUP_OBJECT (agent, label4, "label4");
  GLADE_HOOKUP_OBJECT (agent, label5, "label5");
  GLADE_HOOKUP_OBJECT (agent, label8, "label8");
  GLADE_HOOKUP_OBJECT (agent, spinbutton10, "spinbutton10");
  GLADE_HOOKUP_OBJECT (agent, spinbutton11, "spinbutton11");
  GLADE_HOOKUP_OBJECT (agent, spinbutton12, "spinbutton12");
  GLADE_HOOKUP_OBJECT (agent, label32, "label32");
  GLADE_HOOKUP_OBJECT (agent, button2, "button2");
  GLADE_HOOKUP_OBJECT (agent, combobox8, "combobox8");
  GLADE_HOOKUP_OBJECT (agent, combobox9, "combobox9");
  GLADE_HOOKUP_OBJECT (agent, classcombo, "classcombo");
  GLADE_HOOKUP_OBJECT (agent, label33, "label33");
  GLADE_HOOKUP_OBJECT (agent, Quitter01, "Quitter01");

  return agent;
}

GtkWidget*
create_client (void)
{
  GtkWidget *client;
  GtkWidget *fixed18;
  GtkWidget *entry7;
  GtkObject *spinbutton4_adj;
  GtkWidget *spinbutton4;
  GtkObject *spinbutton5_adj;
  GtkWidget *spinbutton5;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkWidget *label9;
  GtkWidget *label11;
  GtkWidget *label10;
  GtkWidget *label13;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label14;
  GtkWidget *Quitter02;
  GtkWidget *Rechercher2;
  GtkWidget *combobox2;
  GtkWidget *errorclientmessage;
  GtkWidget *allercomboclient;
  GtkWidget *retourcomboclient;

  client = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (client), _("client"));

  fixed18 = gtk_fixed_new ();
  gtk_widget_show (fixed18);
  gtk_container_add (GTK_CONTAINER (client), fixed18);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed18), entry7, 40, 144);
  gtk_widget_set_size_request (entry7, 152, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  spinbutton4_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton4 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton4_adj), 1, 0);
  gtk_widget_show (spinbutton4);
  gtk_fixed_put (GTK_FIXED (fixed18), spinbutton4, 112, 224);
  gtk_widget_set_size_request (spinbutton4, 60, 27);

  spinbutton5_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton5 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton5_adj), 1, 0);
  gtk_widget_show (spinbutton5);
  gtk_fixed_put (GTK_FIXED (fixed18), spinbutton5, 224, 224);
  gtk_widget_set_size_request (spinbutton5, 60, 27);

  spinbutton6_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed18), spinbutton6, 336, 224);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  label9 = gtk_label_new (_("A"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed18), label9, 376, 64);
  gtk_widget_set_size_request (label9, 41, 17);

  label11 = gtk_label_new (_("Date de d\303\251part"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed18), label11, 40, 128);
  gtk_widget_set_size_request (label11, 112, 17);

  label10 = gtk_label_new (_("De"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed18), label10, 32, 64);
  gtk_widget_set_size_request (label10, 49, 17);

  label13 = gtk_label_new (_("classe"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed18), label13, 424, 128);
  gtk_widget_set_size_request (label13, 49, 17);

  label15 = gtk_label_new (_("moins de \n12 ans"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed18), label15, 224, 248);
  gtk_widget_set_size_request (label15, 64, 32);

  label16 = gtk_label_new (_("+ 12ans"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed18), label16, 112, 256);
  gtk_widget_set_size_request (label16, 56, 17);

  label14 = gtk_label_new (_("moins de \n2 ans"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed18), label14, 336, 248);
  gtk_widget_set_size_request (label14, 64, 40);

  Quitter02 = gtk_button_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (Quitter02);
  gtk_fixed_put (GTK_FIXED (fixed18), Quitter02, 16, 296);
  gtk_widget_set_size_request (Quitter02, 66, 29);

  Rechercher2 = gtk_button_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (Rechercher2);
  gtk_fixed_put (GTK_FIXED (fixed18), Rechercher2, 424, 288);
  gtk_widget_set_size_request (Rechercher2, 120, 40);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed18), combobox2, 376, 152);
  gtk_widget_set_size_request (combobox2, 89, 24);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("A"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("B"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("C"));

  errorclientmessage = gtk_label_new ("");
  gtk_widget_show (errorclientmessage);
  gtk_fixed_put (GTK_FIXED (fixed18), errorclientmessage, 120, 24);
  gtk_widget_set_size_request (errorclientmessage, 304, 32);

  allercomboclient = gtk_combo_box_new_text ();
  gtk_widget_show (allercomboclient);
  gtk_fixed_put (GTK_FIXED (fixed18), allercomboclient, 48, 88);
  gtk_widget_set_size_request (allercomboclient, 136, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (allercomboclient), _("tun"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (allercomboclient), _("it"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (allercomboclient), _("mar"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (allercomboclient), _("fr"));

  retourcomboclient = gtk_combo_box_new_text ();
  gtk_widget_show (retourcomboclient);
  gtk_fixed_put (GTK_FIXED (fixed18), retourcomboclient, 336, 96);
  gtk_widget_set_size_request (retourcomboclient, 128, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (retourcomboclient), _("tun"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (retourcomboclient), _("it"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (retourcomboclient), _("mar"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (retourcomboclient), _("fr"));

  g_signal_connect ((gpointer) Quitter02, "clicked",
                    G_CALLBACK (on_Quitter02_clicked),
                    NULL);
  g_signal_connect ((gpointer) Rechercher2, "clicked",
                    G_CALLBACK (on_Rechercher2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (client, client, "client");
  GLADE_HOOKUP_OBJECT (client, fixed18, "fixed18");
  GLADE_HOOKUP_OBJECT (client, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (client, spinbutton4, "spinbutton4");
  GLADE_HOOKUP_OBJECT (client, spinbutton5, "spinbutton5");
  GLADE_HOOKUP_OBJECT (client, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (client, label9, "label9");
  GLADE_HOOKUP_OBJECT (client, label11, "label11");
  GLADE_HOOKUP_OBJECT (client, label10, "label10");
  GLADE_HOOKUP_OBJECT (client, label13, "label13");
  GLADE_HOOKUP_OBJECT (client, label15, "label15");
  GLADE_HOOKUP_OBJECT (client, label16, "label16");
  GLADE_HOOKUP_OBJECT (client, label14, "label14");
  GLADE_HOOKUP_OBJECT (client, Quitter02, "Quitter02");
  GLADE_HOOKUP_OBJECT (client, Rechercher2, "Rechercher2");
  GLADE_HOOKUP_OBJECT (client, combobox2, "combobox2");
  GLADE_HOOKUP_OBJECT (client, errorclientmessage, "errorclientmessage");
  GLADE_HOOKUP_OBJECT (client, allercomboclient, "allercomboclient");
  GLADE_HOOKUP_OBJECT (client, retourcomboclient, "retourcomboclient");

  return client;
}

GtkWidget*
create_geneagent (void)
{
  GtkWidget *geneagent;
  GtkWidget *fixed19;
  GtkWidget *treeview1;
  GtkWidget *entry9;
  GtkWidget *label17;
  GtkWidget *refrech;
  GtkWidget *image1;
  GtkWidget *Quitter1;
  GtkObject *spinbutton17_adj;
  GtkWidget *spinbutton17;
  GtkWidget *label40;
  GtkWidget *button6;

  geneagent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (geneagent), _("geneagent"));

  fixed19 = gtk_fixed_new ();
  gtk_widget_show (fixed19);
  gtk_container_add (GTK_CONTAINER (geneagent), fixed19);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed19), treeview1, 80, 16);
  gtk_widget_set_size_request (treeview1, 376, 264);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed19), entry9, 408, 296);
  gtk_widget_set_size_request (entry9, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  label17 = gtk_label_new (_("Identifiant"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed19), label17, 320, 296);
  gtk_widget_set_size_request (label17, 97, 17);

  refrech = gtk_button_new ();
  gtk_widget_show (refrech);
  gtk_fixed_put (GTK_FIXED (fixed19), refrech, 488, 56);
  gtk_widget_set_size_request (refrech, 74, 29);

  image1 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_container_add (GTK_CONTAINER (refrech), image1);

  Quitter1 = gtk_button_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (Quitter1);
  gtk_fixed_put (GTK_FIXED (fixed19), Quitter1, 16, 368);
  gtk_widget_set_size_request (Quitter1, 66, 29);

  spinbutton17_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton17 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton17_adj), 1, 0);
  gtk_widget_show (spinbutton17);
  gtk_fixed_put (GTK_FIXED (fixed19), spinbutton17, 480, 160);
  gtk_widget_set_size_request (spinbutton17, 60, 27);

  label40 = gtk_label_new (_("numerdo de \nla reservation"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed19), label40, 472, 112);
  gtk_widget_set_size_request (label40, 104, 40);

  button6 = gtk_button_new_with_mnemonic (_("G\303\251n\303\251rer devis"));
  gtk_widget_show (button6);
  gtk_fixed_put (GTK_FIXED (fixed19), button6, 464, 368);
  gtk_widget_set_size_request (button6, 106, 29);

  g_signal_connect ((gpointer) refrech, "clicked",
                    G_CALLBACK (on_refrech_clicked),
                    NULL);
  g_signal_connect ((gpointer) Quitter1, "clicked",
                    G_CALLBACK (on_Quitter1_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (geneagent, geneagent, "geneagent");
  GLADE_HOOKUP_OBJECT (geneagent, fixed19, "fixed19");
  GLADE_HOOKUP_OBJECT (geneagent, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (geneagent, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (geneagent, label17, "label17");
  GLADE_HOOKUP_OBJECT (geneagent, refrech, "refrech");
  GLADE_HOOKUP_OBJECT (geneagent, image1, "image1");
  GLADE_HOOKUP_OBJECT (geneagent, Quitter1, "Quitter1");
  GLADE_HOOKUP_OBJECT (geneagent, spinbutton17, "spinbutton17");
  GLADE_HOOKUP_OBJECT (geneagent, label40, "label40");
  GLADE_HOOKUP_OBJECT (geneagent, button6, "button6");

  return geneagent;
}

GtkWidget*
create_geneclient (void)
{
  GtkWidget *geneclient;
  GtkWidget *fixed20;
  GtkWidget *treeview2;
  GtkWidget *button14;
  GtkWidget *image2;
  GtkWidget *Quitter2;
  GtkObject *spinbutton16_adj;
  GtkWidget *spinbutton16;
  GtkWidget *label39;
  GtkWidget *button7;

  geneclient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (geneclient), _("geneclient"));

  fixed20 = gtk_fixed_new ();
  gtk_widget_show (fixed20);
  gtk_container_add (GTK_CONTAINER (geneclient), fixed20);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed20), treeview2, 48, 8);
  gtk_widget_set_size_request (treeview2, 300, 200);

  button14 = gtk_button_new ();
  gtk_widget_show (button14);
  gtk_fixed_put (GTK_FIXED (fixed20), button14, 392, 40);
  gtk_widget_set_size_request (button14, 74, 29);

  image2 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_container_add (GTK_CONTAINER (button14), image2);

  Quitter2 = gtk_button_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (Quitter2);
  gtk_fixed_put (GTK_FIXED (fixed20), Quitter2, 16, 296);
  gtk_widget_set_size_request (Quitter2, 80, 37);

  spinbutton16_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton16 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton16_adj), 1, 0);
  gtk_widget_show (spinbutton16);
  gtk_fixed_put (GTK_FIXED (fixed20), spinbutton16, 368, 120);
  gtk_widget_set_size_request (spinbutton16, 60, 27);

  label39 = gtk_label_new (_("numero de\nla reservation"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed20), label39, 368, 80);
  gtk_widget_set_size_request (label39, 96, 40);

  button7 = gtk_button_new_with_mnemonic (_("reserver"));
  gtk_widget_show (button7);
  gtk_fixed_put (GTK_FIXED (fixed20), button7, 368, 296);
  gtk_widget_set_size_request (button7, 106, 29);

  g_signal_connect ((gpointer) button14, "clicked",
                    G_CALLBACK (on_button14_clicked),
                    NULL);
  g_signal_connect ((gpointer) Quitter2, "clicked",
                    G_CALLBACK (on_Quitter2_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (geneclient, geneclient, "geneclient");
  GLADE_HOOKUP_OBJECT (geneclient, fixed20, "fixed20");
  GLADE_HOOKUP_OBJECT (geneclient, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (geneclient, button14, "button14");
  GLADE_HOOKUP_OBJECT (geneclient, image2, "image2");
  GLADE_HOOKUP_OBJECT (geneclient, Quitter2, "Quitter2");
  GLADE_HOOKUP_OBJECT (geneclient, spinbutton16, "spinbutton16");
  GLADE_HOOKUP_OBJECT (geneclient, label39, "label39");
  GLADE_HOOKUP_OBJECT (geneclient, button7, "button7");

  return geneclient;
}

GtkWidget*
create_deviswindow (void)
{
  GtkWidget *deviswindow;
  GtkWidget *fixed21;
  GtkWidget *label18;
  GtkWidget *devislabel;

  deviswindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (deviswindow), _("window1"));

  fixed21 = gtk_fixed_new ();
  gtk_widget_show (fixed21);
  gtk_container_add (GTK_CONTAINER (deviswindow), fixed21);

  label18 = gtk_label_new (_("devis"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed21), label18, 136, 8);
  gtk_widget_set_size_request (label18, 128, 40);

  devislabel = gtk_label_new ("");
  gtk_widget_show (devislabel);
  gtk_fixed_put (GTK_FIXED (fixed21), devislabel, 24, 88);
  gtk_widget_set_size_request (devislabel, 361, 360);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (deviswindow, deviswindow, "deviswindow");
  GLADE_HOOKUP_OBJECT (deviswindow, fixed21, "fixed21");
  GLADE_HOOKUP_OBJECT (deviswindow, label18, "label18");
  GLADE_HOOKUP_OBJECT (deviswindow, devislabel, "devislabel");

  return deviswindow;
}

GtkWidget*
create_loginwindow (void)
{
  GtkWidget *loginwindow;
  GtkWidget *fixed22;
  GtkWidget *entry10;
  GtkWidget *entry11;
  GtkWidget *label20;
  GtkWidget *label19;
  GtkWidget *loginbutton;
  GtkWidget *WPlabel;

  loginwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (loginwindow), _("window2"));

  fixed22 = gtk_fixed_new ();
  gtk_widget_show (fixed22);
  gtk_container_add (GTK_CONTAINER (loginwindow), fixed22);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed22), entry10, 120, 104);
  gtk_widget_set_size_request (entry10, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  entry11 = gtk_entry_new ();
  gtk_widget_show (entry11);
  gtk_fixed_put (GTK_FIXED (fixed22), entry11, 128, 208);
  gtk_widget_set_size_request (entry11, 192, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11), 8226);

  label20 = gtk_label_new (_("password"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed22), label20, 120, 184);
  gtk_widget_set_size_request (label20, 73, 25);

  label19 = gtk_label_new (_("login"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed22), label19, 104, 72);
  gtk_widget_set_size_request (label19, 89, 40);

  loginbutton = gtk_button_new_with_mnemonic (_("login"));
  gtk_widget_show (loginbutton);
  gtk_fixed_put (GTK_FIXED (fixed22), loginbutton, 176, 312);
  gtk_widget_set_size_request (loginbutton, 66, 29);

  WPlabel = gtk_label_new ("");
  gtk_widget_show (WPlabel);
  gtk_fixed_put (GTK_FIXED (fixed22), WPlabel, 136, 256);
  gtk_widget_set_size_request (WPlabel, 216, 40);

  g_signal_connect ((gpointer) loginbutton, "clicked",
                    G_CALLBACK (on_loginbutton_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (loginwindow, loginwindow, "loginwindow");
  GLADE_HOOKUP_OBJECT (loginwindow, fixed22, "fixed22");
  GLADE_HOOKUP_OBJECT (loginwindow, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (loginwindow, entry11, "entry11");
  GLADE_HOOKUP_OBJECT (loginwindow, label20, "label20");
  GLADE_HOOKUP_OBJECT (loginwindow, label19, "label19");
  GLADE_HOOKUP_OBJECT (loginwindow, loginbutton, "loginbutton");
  GLADE_HOOKUP_OBJECT (loginwindow, WPlabel, "WPlabel");

  return loginwindow;
}

GtkWidget*
create_aller_allerretour_window (void)
{
  GtkWidget *aller_allerretour_window;
  GtkWidget *fixed23;
  GtkWidget *allerbutton;
  GtkWidget *quitter3button;
  GtkWidget *allerretourbutton;
  GtkWidget *modifier_reservation_button;

  aller_allerretour_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (aller_allerretour_window), _("window3"));

  fixed23 = gtk_fixed_new ();
  gtk_widget_show (fixed23);
  gtk_container_add (GTK_CONTAINER (aller_allerretour_window), fixed23);

  allerbutton = gtk_button_new_with_mnemonic (_("aller"));
  gtk_widget_show (allerbutton);
  gtk_fixed_put (GTK_FIXED (fixed23), allerbutton, 72, 48);
  gtk_widget_set_size_request (allerbutton, 232, 80);

  quitter3button = gtk_button_new_with_mnemonic (_("quitter"));
  gtk_widget_show (quitter3button);
  gtk_fixed_put (GTK_FIXED (fixed23), quitter3button, 152, 400);
  gtk_widget_set_size_request (quitter3button, 74, 29);

  allerretourbutton = gtk_button_new_with_mnemonic (_("aller / retour"));
  gtk_widget_show (allerretourbutton);
  gtk_fixed_put (GTK_FIXED (fixed23), allerretourbutton, 88, 168);
  gtk_widget_set_size_request (allerretourbutton, 216, 80);

  modifier_reservation_button = gtk_button_new_with_mnemonic (_("modifier reservation"));
  gtk_widget_show (modifier_reservation_button);
  gtk_fixed_put (GTK_FIXED (fixed23), modifier_reservation_button, 88, 288);
  gtk_widget_set_size_request (modifier_reservation_button, 208, 80);

  g_signal_connect ((gpointer) allerbutton, "clicked",
                    G_CALLBACK (on_allerbutton_clicked),
                    NULL);
  g_signal_connect ((gpointer) quitter3button, "clicked",
                    G_CALLBACK (on_quitter3button_clicked),
                    NULL);
  g_signal_connect ((gpointer) allerretourbutton, "clicked",
                    G_CALLBACK (on_allerretourbutton_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier_reservation_button, "clicked",
                    G_CALLBACK (on_modifier_reservation_button_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (aller_allerretour_window, aller_allerretour_window, "aller_allerretour_window");
  GLADE_HOOKUP_OBJECT (aller_allerretour_window, fixed23, "fixed23");
  GLADE_HOOKUP_OBJECT (aller_allerretour_window, allerbutton, "allerbutton");
  GLADE_HOOKUP_OBJECT (aller_allerretour_window, quitter3button, "quitter3button");
  GLADE_HOOKUP_OBJECT (aller_allerretour_window, allerretourbutton, "allerretourbutton");
  GLADE_HOOKUP_OBJECT (aller_allerretour_window, modifier_reservation_button, "modifier_reservation_button");

  return aller_allerretour_window;
}

GtkWidget*
create_allerretourclient (void)
{
  GtkWidget *allerretourclient;
  GtkWidget *fixed24;
  GtkWidget *entry14;
  GtkWidget *entry15;
  GtkObject *spinbutton7_adj;
  GtkWidget *spinbutton7;
  GtkObject *spinbutton8_adj;
  GtkWidget *spinbutton8;
  GtkObject *spinbutton9_adj;
  GtkWidget *spinbutton9;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *label26;
  GtkWidget *label27;
  GtkWidget *label28;
  GtkWidget *label29;
  GtkWidget *combobox3;
  GtkWidget *combobox6;
  GtkWidget *combobox7;
  GtkWidget *label31;
  GtkWidget *button12;
  GtkWidget *button11;

  allerretourclient = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (allerretourclient), _("client"));

  fixed24 = gtk_fixed_new ();
  gtk_widget_show (fixed24);
  gtk_container_add (GTK_CONTAINER (allerretourclient), fixed24);

  entry14 = gtk_entry_new ();
  gtk_widget_show (entry14);
  gtk_fixed_put (GTK_FIXED (fixed24), entry14, 40, 144);
  gtk_widget_set_size_request (entry14, 152, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry14), 8226);

  entry15 = gtk_entry_new ();
  gtk_widget_show (entry15);
  gtk_fixed_put (GTK_FIXED (fixed24), entry15, 232, 144);
  gtk_widget_set_size_request (entry15, 144, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry15), 8226);

  spinbutton7_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_adj), 1, 0);
  gtk_widget_show (spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed24), spinbutton7, 112, 224);
  gtk_widget_set_size_request (spinbutton7, 60, 27);

  spinbutton8_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton8 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton8_adj), 1, 0);
  gtk_widget_show (spinbutton8);
  gtk_fixed_put (GTK_FIXED (fixed24), spinbutton8, 224, 224);
  gtk_widget_set_size_request (spinbutton8, 60, 27);

  spinbutton9_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton9 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton9_adj), 1, 0);
  gtk_widget_show (spinbutton9);
  gtk_fixed_put (GTK_FIXED (fixed24), spinbutton9, 336, 224);
  gtk_widget_set_size_request (spinbutton9, 60, 27);

  label22 = gtk_label_new (_("A"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed24), label22, 376, 64);
  gtk_widget_set_size_request (label22, 41, 17);

  label23 = gtk_label_new (_("Date de d\303\251part"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed24), label23, 40, 128);
  gtk_widget_set_size_request (label23, 112, 17);

  label24 = gtk_label_new (_("De"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed24), label24, 32, 64);
  gtk_widget_set_size_request (label24, 49, 17);

  label25 = gtk_label_new (_("Date d'arriv\303\251e"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed24), label25, 232, 128);
  gtk_widget_set_size_request (label25, 104, 17);

  label26 = gtk_label_new (_("classe"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed24), label26, 424, 128);
  gtk_widget_set_size_request (label26, 49, 17);

  label27 = gtk_label_new (_("moins de \n12 ans"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed24), label27, 224, 248);
  gtk_widget_set_size_request (label27, 64, 32);

  label28 = gtk_label_new (_("+ 12ans"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed24), label28, 112, 256);
  gtk_widget_set_size_request (label28, 56, 17);

  label29 = gtk_label_new (_("moins de \n2 ans"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed24), label29, 336, 248);
  gtk_widget_set_size_request (label29, 64, 40);

  combobox3 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox3);
  gtk_fixed_put (GTK_FIXED (fixed24), combobox3, 432, 152);
  gtk_widget_set_size_request (combobox3, 33, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("A"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("B"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox3), _("C"));

  combobox6 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox6);
  gtk_fixed_put (GTK_FIXED (fixed24), combobox6, 48, 88);
  gtk_widget_set_size_request (combobox6, 136, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("tun"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("it"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("mar"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox6), _("fr"));

  combobox7 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox7);
  gtk_fixed_put (GTK_FIXED (fixed24), combobox7, 384, 88);
  gtk_widget_set_size_request (combobox7, 128, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("tun"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("it"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("mar"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox7), _("fr"));

  label31 = gtk_label_new ("");
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed24), label31, 192, 24);
  gtk_widget_set_size_request (label31, 168, 40);

  button12 = gtk_button_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (button12);
  gtk_fixed_put (GTK_FIXED (fixed24), button12, 440, 352);
  gtk_widget_set_size_request (button12, 120, 40);

  button11 = gtk_button_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (button11);
  gtk_fixed_put (GTK_FIXED (fixed24), button11, 16, 368);
  gtk_widget_set_size_request (button11, 66, 29);

  g_signal_connect ((gpointer) button12, "clicked",
                    G_CALLBACK (on_button12_clicked),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_button11_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (allerretourclient, allerretourclient, "allerretourclient");
  GLADE_HOOKUP_OBJECT (allerretourclient, fixed24, "fixed24");
  GLADE_HOOKUP_OBJECT (allerretourclient, entry14, "entry14");
  GLADE_HOOKUP_OBJECT (allerretourclient, entry15, "entry15");
  GLADE_HOOKUP_OBJECT (allerretourclient, spinbutton7, "spinbutton7");
  GLADE_HOOKUP_OBJECT (allerretourclient, spinbutton8, "spinbutton8");
  GLADE_HOOKUP_OBJECT (allerretourclient, spinbutton9, "spinbutton9");
  GLADE_HOOKUP_OBJECT (allerretourclient, label22, "label22");
  GLADE_HOOKUP_OBJECT (allerretourclient, label23, "label23");
  GLADE_HOOKUP_OBJECT (allerretourclient, label24, "label24");
  GLADE_HOOKUP_OBJECT (allerretourclient, label25, "label25");
  GLADE_HOOKUP_OBJECT (allerretourclient, label26, "label26");
  GLADE_HOOKUP_OBJECT (allerretourclient, label27, "label27");
  GLADE_HOOKUP_OBJECT (allerretourclient, label28, "label28");
  GLADE_HOOKUP_OBJECT (allerretourclient, label29, "label29");
  GLADE_HOOKUP_OBJECT (allerretourclient, combobox3, "combobox3");
  GLADE_HOOKUP_OBJECT (allerretourclient, combobox6, "combobox6");
  GLADE_HOOKUP_OBJECT (allerretourclient, combobox7, "combobox7");
  GLADE_HOOKUP_OBJECT (allerretourclient, label31, "label31");
  GLADE_HOOKUP_OBJECT (allerretourclient, button12, "button12");
  GLADE_HOOKUP_OBJECT (allerretourclient, button11, "button11");

  return allerretourclient;
}

GtkWidget*
create_geneclientretour (void)
{
  GtkWidget *geneclientretour;
  GtkWidget *fixed25;
  GtkWidget *treeview3;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *treeview4;
  GtkWidget *button17;
  GtkWidget *image3;
  GtkWidget *button15;
  GtkObject *spinbutton14_adj;
  GtkWidget *spinbutton14;
  GtkObject *spinbutton15_adj;
  GtkWidget *spinbutton15;
  GtkWidget *button16;

  geneclientretour = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (geneclientretour), _("window1"));

  fixed25 = gtk_fixed_new ();
  gtk_widget_show (fixed25);
  gtk_container_add (GTK_CONTAINER (geneclientretour), fixed25);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed25), treeview3, 64, 80);
  gtk_widget_set_size_request (treeview3, 300, 200);

  label34 = gtk_label_new (_("aller"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed25), label34, 48, 32);
  gtk_widget_set_size_request (label34, 49, 17);

  label35 = gtk_label_new (_("retour"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed25), label35, 400, 24);
  gtk_widget_set_size_request (label35, 49, 17);

  treeview4 = gtk_tree_view_new ();
  gtk_widget_show (treeview4);
  gtk_fixed_put (GTK_FIXED (fixed25), treeview4, 432, 80);
  gtk_widget_set_size_request (treeview4, 300, 200);

  button17 = gtk_button_new ();
  gtk_widget_show (button17);
  gtk_fixed_put (GTK_FIXED (fixed25), button17, 376, 312);
  gtk_widget_set_size_request (button17, 74, 29);

  image3 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_container_add (GTK_CONTAINER (button17), image3);

  button15 = gtk_button_new_with_mnemonic (_("quitter"));
  gtk_widget_show (button15);
  gtk_fixed_put (GTK_FIXED (fixed25), button15, 128, 320);
  gtk_widget_set_size_request (button15, 74, 29);

  spinbutton14_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton14 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton14_adj), 1, 0);
  gtk_widget_show (spinbutton14);
  gtk_fixed_put (GTK_FIXED (fixed25), spinbutton14, 664, 40);
  gtk_widget_set_size_request (spinbutton14, 60, 27);

  spinbutton15_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton15 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton15_adj), 1, 0);
  gtk_widget_show (spinbutton15);
  gtk_fixed_put (GTK_FIXED (fixed25), spinbutton15, 104, 24);
  gtk_widget_set_size_request (spinbutton15, 60, 27);

  button16 = gtk_button_new_with_mnemonic (_("reserver"));
  gtk_widget_show (button16);
  gtk_fixed_put (GTK_FIXED (fixed25), button16, 632, 328);
  gtk_widget_set_size_request (button16, 74, 29);

  g_signal_connect ((gpointer) button17, "clicked",
                    G_CALLBACK (on_button17_clicked),
                    NULL);
  g_signal_connect ((gpointer) button15, "clicked",
                    G_CALLBACK (on_button15_clicked),
                    NULL);
  g_signal_connect ((gpointer) button16, "clicked",
                    G_CALLBACK (on_button16_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (geneclientretour, geneclientretour, "geneclientretour");
  GLADE_HOOKUP_OBJECT (geneclientretour, fixed25, "fixed25");
  GLADE_HOOKUP_OBJECT (geneclientretour, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (geneclientretour, label34, "label34");
  GLADE_HOOKUP_OBJECT (geneclientretour, label35, "label35");
  GLADE_HOOKUP_OBJECT (geneclientretour, treeview4, "treeview4");
  GLADE_HOOKUP_OBJECT (geneclientretour, button17, "button17");
  GLADE_HOOKUP_OBJECT (geneclientretour, image3, "image3");
  GLADE_HOOKUP_OBJECT (geneclientretour, button15, "button15");
  GLADE_HOOKUP_OBJECT (geneclientretour, spinbutton14, "spinbutton14");
  GLADE_HOOKUP_OBJECT (geneclientretour, spinbutton15, "spinbutton15");
  GLADE_HOOKUP_OBJECT (geneclientretour, button16, "button16");

  return geneclientretour;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed26;
  GtkObject *spinbutton13_adj;
  GtkWidget *spinbutton13;
  GtkWidget *buttonmodifreservation;
  GtkWidget *image6;
  GtkWidget *label36;
  GtkWidget *buttonquit;
  GtkWidget *buttonrefreshreservation;
  GtkWidget *image7;
  GtkWidget *label37;
  GtkWidget *buttonsupprimreservation;
  GtkWidget *image4;
  GtkWidget *label38;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  fixed26 = gtk_fixed_new ();
  gtk_widget_show (fixed26);
  gtk_container_add (GTK_CONTAINER (window2), fixed26);

  spinbutton13_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton13 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton13_adj), 1, 0);
  gtk_widget_show (spinbutton13);
  gtk_fixed_put (GTK_FIXED (fixed26), spinbutton13, 136, 520);
  gtk_widget_set_size_request (spinbutton13, 60, 27);

  buttonmodifreservation = gtk_button_new ();
  gtk_widget_show (buttonmodifreservation);
  gtk_fixed_put (GTK_FIXED (fixed26), buttonmodifreservation, 288, 584);
  gtk_widget_set_size_request (buttonmodifreservation, 74, 29);

  image6 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_container_add (GTK_CONTAINER (buttonmodifreservation), image6);

  label36 = gtk_label_new (_("modification"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed26), label36, 24, 40);
  gtk_widget_set_size_request (label36, 472, 64);

  buttonquit = gtk_button_new_with_mnemonic (_("quitter"));
  gtk_widget_show (buttonquit);
  gtk_fixed_put (GTK_FIXED (fixed26), buttonquit, 96, 664);
  gtk_widget_set_size_request (buttonquit, 74, 29);

  buttonrefreshreservation = gtk_button_new ();
  gtk_widget_show (buttonrefreshreservation);
  gtk_fixed_put (GTK_FIXED (fixed26), buttonrefreshreservation, 304, 672);
  gtk_widget_set_size_request (buttonrefreshreservation, 74, 29);

  image7 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_container_add (GTK_CONTAINER (buttonrefreshreservation), image7);

  label37 = gtk_label_new (_("num reservation"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed26), label37, 248, 520);
  gtk_widget_set_size_request (label37, 200, 24);

  buttonsupprimreservation = gtk_button_new ();
  gtk_widget_show (buttonsupprimreservation);
  gtk_fixed_put (GTK_FIXED (fixed26), buttonsupprimreservation, 112, 584);
  gtk_widget_set_size_request (buttonsupprimreservation, 74, 29);

  image4 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_container_add (GTK_CONTAINER (buttonsupprimreservation), image4);

  label38 = gtk_label_new ("");
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed26), label38, 48, 112);
  gtk_widget_set_size_request (label38, 448, 376);

  g_signal_connect ((gpointer) buttonmodifreservation, "clicked",
                    G_CALLBACK (on_buttonmodifreservation_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonquit, "clicked",
                    G_CALLBACK (on_buttonquit_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonrefreshreservation, "clicked",
                    G_CALLBACK (on_buttonrefreshreservation_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonsupprimreservation, "clicked",
                    G_CALLBACK (on_buttonsupprimreservation_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed26, "fixed26");
  GLADE_HOOKUP_OBJECT (window2, spinbutton13, "spinbutton13");
  GLADE_HOOKUP_OBJECT (window2, buttonmodifreservation, "buttonmodifreservation");
  GLADE_HOOKUP_OBJECT (window2, image6, "image6");
  GLADE_HOOKUP_OBJECT (window2, label36, "label36");
  GLADE_HOOKUP_OBJECT (window2, buttonquit, "buttonquit");
  GLADE_HOOKUP_OBJECT (window2, buttonrefreshreservation, "buttonrefreshreservation");
  GLADE_HOOKUP_OBJECT (window2, image7, "image7");
  GLADE_HOOKUP_OBJECT (window2, label37, "label37");
  GLADE_HOOKUP_OBJECT (window2, buttonsupprimreservation, "buttonsupprimreservation");
  GLADE_HOOKUP_OBJECT (window2, image4, "image4");
  GLADE_HOOKUP_OBJECT (window2, label38, "label38");

  return window2;
}

