/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_agent (void);
GtkWidget* create_client (void);
GtkWidget* create_geneagent (void);
GtkWidget* create_geneclient (void);
GtkWidget* create_deviswindow (void);
GtkWidget* create_loginwindow (void);
GtkWidget* create_aller_allerretour_window (void);
GtkWidget* create_allerretourclient (void);
GtkWidget* create_geneclientretour (void);
GtkWidget* create_window2 (void);
